apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: travel-planner-api-pdb
  namespace: travel-planner
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: travel-planner-api
