apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: travel-planner
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
